/**
 * Clipboard Formatter for Travel Itineraries
 *
 * Formats travel itineraries as plain text for easy copy-paste
 * into visa application forms and other documents.
 */

import { NormalizedItinerary } from './travelPlanner';

interface ClipboardFormatterOptions {
  destination: string;
  travelDates: { start: string; end: string };
  tripPurpose: string;
  budget?: string;
  nationality?: string;
  travelerCount?: string;
}

export function formatItineraryForClipboard(
  itinerary: NormalizedItinerary,
  options: ClipboardFormatterOptions
): string {
  const lines: string[] = [];

  // Header
  lines.push('═══════════════════════════════════════════════════');
  lines.push('           TRAVEL ITINERARY - VISA APPLICATION');
  lines.push('              Generated by MYDSCVR AI');
  lines.push('═══════════════════════════════════════════════════');
  lines.push('');

  // Trip Summary
  lines.push('TRIP SUMMARY');
  lines.push('─────────────────────────────────────────────────');
  lines.push(`Destination:        ${options.destination}`);
  lines.push(`Travel Dates:       ${formatDate(options.travelDates.start)} to ${formatDate(options.travelDates.end)}`);
  lines.push(`Duration:           ${calculateDuration(options.travelDates.start, options.travelDates.end)} days`);
  lines.push(`Purpose:            ${options.tripPurpose}`);
  lines.push(`Number of Travelers: ${options.travelerCount || '1'}`);

  if (options.nationality) {
    lines.push(`Nationality:        ${options.nationality}`);
  }

  if (options.budget) {
    lines.push(`Budget Level:       ${options.budget}`);
  }

  lines.push('');

  // Flights
  if (itinerary.flights && itinerary.flights.length > 0) {
    lines.push('✈ FLIGHT DETAILS');
    lines.push('─────────────────────────────────────────────────');

    itinerary.flights.forEach((flight, index) => {
      lines.push(`${index + 1}. ${flight.airline || 'Airline TBD'}`);
      lines.push(`   Route:          ${flight.departure || 'N/A'} → ${flight.arrival || 'N/A'}`);

      if (flight.price) {
        lines.push(`   Price:          $${flight.price} USD`);
      }

      lines.push('');
    });
  }

  // Accommodation
  if (itinerary.hotels && itinerary.hotels.length > 0) {
    lines.push('🏨 ACCOMMODATION');
    lines.push('─────────────────────────────────────────────────');

    itinerary.hotels.forEach((hotel, index) => {
      lines.push(`${index + 1}. ${hotel.name || 'Hotel TBD'}`);
      lines.push(`   Location:       ${hotel.location || 'Location TBD'}`);
      lines.push(`   Duration:       ${hotel.nights} night${hotel.nights > 1 ? 's' : ''}`);

      if (hotel.price) {
        lines.push(`   Total Cost:     $${hotel.price} USD`);
      }

      lines.push('');
    });
  }

  // Daily Itinerary
  if (itinerary.dailyPlan && itinerary.dailyPlan.length > 0) {
    lines.push('📅 DAILY ITINERARY');
    lines.push('─────────────────────────────────────────────────');
    lines.push('');

    itinerary.dailyPlan.forEach((day) => {
      lines.push(`DAY ${day.day} - ${day.date}`);
      lines.push(`Location: ${day.city || 'TBD'}${day.country ? `, ${day.country}` : ''}`);
      lines.push('');

      if (day.activities && day.activities.length > 0) {
        lines.push('Activities:');
        day.activities.forEach((activity) => {
          const time = activity.time || 'TBD';
          const location = activity.location ? ` at ${activity.location}` : '';
          const description = activity.description ? ` - ${activity.description}` : '';

          lines.push(`  • ${time} - ${activity.name}${location}${description}`);
        });
        lines.push('');
      }

      if (day.accommodation) {
        lines.push(`Overnight: ${day.accommodation}`);
        lines.push('');
      }

      lines.push('');
    });
  }

  // Activities Summary (if not in dailyPlan)
  if (itinerary.activities && itinerary.activities.length > 0 && (!itinerary.dailyPlan || itinerary.dailyPlan.length === 0)) {
    lines.push('PLANNED ACTIVITIES');
    lines.push('─────────────────────────────────────────────────');

    itinerary.activities.forEach((activity) => {
      lines.push(`Day ${activity.day}: ${activity.name}`);

      if (activity.description) {
        lines.push(`   ${activity.description}`);
      }

      if (activity.time) {
        lines.push(`   Time: ${activity.time}`);
      }

      if (activity.location) {
        lines.push(`   Location: ${activity.location}`);
      }

      lines.push('');
    });
  }

  // Cost Summary
  const totalFlightCost = itinerary.flights.reduce((sum, f) => sum + (f.price || 0), 0);
  const totalHotelCost = itinerary.hotels.reduce((sum, h) => sum + (h.price || 0), 0);
  const totalCost = totalFlightCost + totalHotelCost;

  if (totalCost > 0) {
    lines.push('💰 COST SUMMARY');
    lines.push('─────────────────────────────────────────────────');
    lines.push(`Flight Costs:         $${totalFlightCost.toFixed(2)} USD`);
    lines.push(`Accommodation Costs:  $${totalHotelCost.toFixed(2)} USD`);
    lines.push(`─────────────────────────────────────────────────`);
    lines.push(`ESTIMATED TOTAL:      $${totalCost.toFixed(2)} USD`);
    lines.push('');
  }

  // Footer
  lines.push('═══════════════════════════════════════════════════');
  lines.push(`Generated on: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push('This itinerary was generated by MYDSCVR AI for visa application purposes.');
  lines.push('═══════════════════════════════════════════════════');

  return lines.join('\n');
}

// Helper function to copy to clipboard
export async function copyItineraryToClipboard(
  itinerary: NormalizedItinerary,
  options: ClipboardFormatterOptions
): Promise<boolean> {
  try {
    const text = formatItineraryForClipboard(itinerary, options);
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

// Helper function to format dates
function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
}

// Helper function to calculate duration
function calculateDuration(startDate: string, endDate: string): number {
  const start = new Date(startDate);
  const end = new Date(endDate);
  return Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
}
