/**
 * PDF Generation Utility for Travel Itineraries
 *
 * Generates professionally formatted, visa-ready PDF itineraries
 * with flights, hotels, daily activities, and pricing details.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { NormalizedItinerary } from './travelPlanner';

interface PDFGenerationOptions {
  destination: string;
  travelDates: { start: string; end: string };
  tripPurpose: string;
  budget?: string;
  nationality?: string;
  travelerCount?: string;
}

export function generateItineraryPDF(
  itinerary: NormalizedItinerary,
  options: PDFGenerationOptions
): void {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // === HEADER / BRANDING ===
  doc.setFillColor(79, 70, 229); // Indigo gradient color
  doc.rect(0, 0, pageWidth, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('TRAVEL ITINERARY', pageWidth / 2, 15, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Visa-Ready Travel Plan | Generated by MYDSCVR AI', pageWidth / 2, 25, { align: 'center' });

  yPosition = 45;

  // === TRIP SUMMARY SECTION ===
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Trip Summary', 15, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const summaryData = [
    ['Destination:', options.destination],
    ['Travel Dates:', `${formatDate(options.travelDates.start)} to ${formatDate(options.travelDates.end)}`],
    ['Duration:', `${calculateDuration(options.travelDates.start, options.travelDates.end)} days`],
    ['Purpose:', options.tripPurpose],
    ['Travelers:', options.travelerCount || '1'],
    ...(options.nationality ? [['Nationality:', options.nationality]] : []),
    ...(options.budget ? [['Budget Level:', options.budget]] : []),
  ];

  summaryData.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 15, yPosition);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 55, yPosition);
    yPosition += 6;
  });

  yPosition += 5;

  // === FLIGHT DETAILS ===
  if (itinerary.flights && itinerary.flights.length > 0) {
    yPosition = checkPageBreak(doc, yPosition, 60);

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(79, 70, 229);
    doc.text('✈ Flight Details', 15, yPosition);
    yPosition += 8;

    itinerary.flights.forEach((flight, index) => {
      yPosition = checkPageBreak(doc, yPosition, 25);

      doc.setFillColor(245, 245, 250);
      doc.rect(15, yPosition - 5, pageWidth - 30, 20, 'F');

      doc.setTextColor(0, 0, 0);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`${index + 1}. ${flight.airline || 'Airline TBD'}`, 18, yPosition);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(`${flight.departure || 'N/A'} → ${flight.arrival || 'N/A'}`, 18, yPosition + 5);

      if (flight.price) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(79, 70, 229);
        doc.text(`$${flight.price}`, pageWidth - 25, yPosition, { align: 'right' });
      }

      yPosition += 25;
    });
  }

  // === ACCOMMODATION DETAILS ===
  if (itinerary.hotels && itinerary.hotels.length > 0) {
    yPosition = checkPageBreak(doc, yPosition, 60);

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(147, 51, 234); // Purple
    doc.text('🏨 Accommodation', 15, yPosition);
    yPosition += 8;

    itinerary.hotels.forEach((hotel, index) => {
      yPosition = checkPageBreak(doc, yPosition, 25);

      doc.setFillColor(250, 245, 255);
      doc.rect(15, yPosition - 5, pageWidth - 30, 20, 'F');

      doc.setTextColor(0, 0, 0);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`${index + 1}. ${hotel.name || 'Hotel TBD'}`, 18, yPosition);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(`${hotel.location || 'Location TBD'} • ${hotel.nights} night${hotel.nights > 1 ? 's' : ''}`, 18, yPosition + 5);

      if (hotel.price) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(147, 51, 234);
        doc.text(`$${hotel.price}`, pageWidth - 25, yPosition, { align: 'right' });
      }

      yPosition += 25;
    });
  }

  // === DAILY ITINERARY ===
  if (itinerary.dailyPlan && itinerary.dailyPlan.length > 0) {
    yPosition = checkPageBreak(doc, yPosition, 80, true);

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(16, 185, 129); // Green
    doc.text('📅 Daily Itinerary', 15, yPosition);
    yPosition += 10;

    itinerary.dailyPlan.forEach((day) => {
      yPosition = checkPageBreak(doc, yPosition, 50);

      // Day header
      doc.setFillColor(16, 185, 129);
      doc.rect(15, yPosition - 6, pageWidth - 30, 10, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`Day ${day.day} - ${day.date}`, 18, yPosition);
      doc.text(`${day.city || ''}${day.country ? `, ${day.country}` : ''}`, pageWidth - 18, yPosition, { align: 'right' });

      yPosition += 10;

      // Activities
      if (day.activities && day.activities.length > 0) {
        day.activities.forEach((activity) => {
          yPosition = checkPageBreak(doc, yPosition, 12);

          doc.setTextColor(0, 0, 0);
          doc.setFontSize(9);
          doc.setFont('helvetica', 'bold');
          doc.text(`${activity.time || 'TBD'}`, 18, yPosition);

          doc.setFont('helvetica', 'normal');
          const activityText = `${activity.name}${activity.location ? ' at ' + activity.location : ''}`;
          const splitText = doc.splitTextToSize(activityText, pageWidth - 50);
          doc.text(splitText, 38, yPosition);

          yPosition += 5 * splitText.length;
        });
      }

      if (day.accommodation) {
        yPosition = checkPageBreak(doc, yPosition, 8);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(100, 100, 100);
        doc.text(`Overnight: ${day.accommodation}`, 18, yPosition);
        yPosition += 6;
      }

      yPosition += 8;
    });
  }

  // === TOTAL COST SUMMARY ===
  const totalFlightCost = itinerary.flights.reduce((sum, f) => sum + (f.price || 0), 0);
  const totalHotelCost = itinerary.hotels.reduce((sum, h) => sum + (h.price || 0), 0);
  const totalCost = totalFlightCost + totalHotelCost;

  if (totalCost > 0) {
    yPosition = checkPageBreak(doc, yPosition, 40);

    doc.setFillColor(245, 245, 250);
    doc.rect(15, yPosition - 5, pageWidth - 30, 35, 'F');

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Cost Summary', 18, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Flight Costs:`, 18, yPosition);
    doc.text(`$${totalFlightCost.toFixed(2)}`, pageWidth - 25, yPosition, { align: 'right' });
    yPosition += 6;

    doc.text(`Accommodation Costs:`, 18, yPosition);
    doc.text(`$${totalHotelCost.toFixed(2)}`, pageWidth - 25, yPosition, { align: 'right' });
    yPosition += 6;

    doc.setFont('helvetica', 'bold');
    doc.text(`Estimated Total:`, 18, yPosition);
    doc.setTextColor(79, 70, 229);
    doc.text(`$${totalCost.toFixed(2)} USD`, pageWidth - 25, yPosition, { align: 'right' });
    yPosition += 10;
  }

  // === FOOTER ===
  const pageCount = (doc as any).internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Generated on ${new Date().toLocaleDateString()} | MYDSCVR Travel Itinerary | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // === SAVE PDF ===
  const fileName = `Travel-Itinerary-${options.destination.replace(/\s+/g, '-')}-${options.travelDates.start}.pdf`;
  doc.save(fileName);
}

// Helper function to check if page break is needed
function checkPageBreak(doc: jsPDF, yPosition: number, spaceNeeded: number, forceNewPage = false): number {
  const pageHeight = doc.internal.pageSize.getHeight();

  if (forceNewPage || yPosition + spaceNeeded > pageHeight - 20) {
    doc.addPage();
    return 20;
  }

  return yPosition;
}

// Helper function to format dates
function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
}

// Helper function to calculate duration
function calculateDuration(startDate: string, endDate: string): number {
  const start = new Date(startDate);
  const end = new Date(endDate);
  return Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
}
